pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

include ':app'

// O Flutter usa este arquivo para carregar a lista de plugins externos.
// A sintaxe abaixo é o padrão moderno para inclusão de plugins
def flutterProject = project(':app').hasProperty('flutter') ? project(':app').property('flutter') : null
if (flutterProject?.with='flutter-plugin') {
    apply from: flutterProject
} else if (flutterProject) {
    apply from: "$flutterProject"
}

// Mantenha esta linha para carregar os plugins do pubspec.yaml
apply from: new File(settingsDir, '.flutter-plugins-dependencies.gradle')
